# Site settings
title: YANG Chen's Blog
SEOTitle: 杨晨的博客
header-img: img/bg-index.jpg
email: a4100yc@gmail.com
description: "Chen Yang, University of Florida, https://chenyang-ece.github.io "
keyword: ""
url: "https://chenyang-ece.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
#weibo_username:     huxpro
zhihu_username:     yang-guo-qian-11
github_username:    chenyang-ece
twitter_username:   Chen25565903
#facebook_username:  huxpro
linkedin_username:  chen-yang-a4100yc



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 6
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: chennoblog

# Valine评论系统开关
valine:
  enable: true
  appid:  uLpLYas1c8GUDynItTjAMHsv-gzGzoHsz
  appkey: F6ayUuXO9I9PENMcOuv7GyKV
  placeholder: 请在此处留言！昵称填QQ号自动获取QQ头像及昵称！  # comment box placeholder
  avatar: ''   # gravatar style
  guest_info: 昵称(或QQ号), 邮件, 网址(http://) # custom comment header
  pageSize: 5 # pagination size
  # path: window.location.pathname #  v1.4.0+不要使用参数“app_key: '{{ site.valine.appkey }}',”
  recordIP: true # 是否记录评论者IP
  enableQQ: true # 是否启用昵称框自动获取QQ昵称和QQ头像, 默认关闭
  avatar_cdn: https://sdn.geekzu.org/avatar/    # gravatar头像镜像
  serverURLs: https://ulplyas1.lc-cn-n1-shared.com # 把前8位字符替换成你自己AppID的前8位字符，leancloud国际版添加该参数，国内版无需


# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
ba_track_id: 3b260a0f1b96afd8ce63e6ea547b9780

# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "
<b>Thomas YANG</b><br>
三星半导体（中国）研究院
<br>
CIS Technical Manager
<br>

电话: 86 15004103560<br>
邮箱: a4100yc@outlook.com<br>
地址: 北京市朝阳区
"
sidebar-avatar: /img/TS.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: false



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
  {
    title: "Samsung Semiconductor",              # 要显示的名称
    href: "https://semiconductor.samsung.com/cn/"   # 好友的博客链接
   },

   {
    title: "Xiaomi Tech",              # 要显示的名称
    href: "https://www.mi.com/"   # 好友的博客链接
   },
   {
        title: "University of Florida",              # 要显示的名称
        href: "http://www.ufl.edu/"   # 好友的博客链接
    },
    {
        title: "UF ECE",              # 要显示的名称
        href: "https://www.ece.ufl.edu/"    # 好友的博客链接
    },
    {
    title: "Google Translate",              # 要显示的名称
    href: "https://translate.google.cn/"    # 好友的博客链接
    },
]
